export const translations = {
  sv: {
    common: {
      bookNow: "Boka tid",
      readMore: "Läs mer",
      loading: "Laddar...",
      error: "Ett fel uppstod",
      success: "Framgång!",
      submit: "Skicka",
      cancel: "Avbryt",
      next: "Nästa",
      previous: "Föregående",
      home: "Hem",
      services: "Tjänster",
      booking: "Bokning",
      contact: "Kontakt",
      admin: "Admin",
      login: "Logga in",
      logout: "Logga ut",
      email: "E-post",
      password: "Lösenord",
      name: "Namn",
      phone: "Telefon",
      date: "Datum",
      time: "Tid",
      service: "Tjänst",
      barber: "Barberare",
      duration: "Varaktighet",
      price: "Pris",
      minutes: "minuter",
      sek: "kr",
    },
    nav: {
      home: "Hem",
      services: "Tjänster",
      booking: "Boka tid",
      contact: "Kontakt",
    },
    home: {
      hero: {
        title: "Premium Barberupplevelse",
        subtitle: "Där stil möter tradition",
        cta: "Boka tid nu",
      },
      services: {
        title: "Våra tjänster",
        subtitle: "Professionell skönhetsvård för män",
        viewAll: "Se alla tjänster",
      },
      testimonials: {
        title: "Vad våra kunder säger",
        subtitle: "Omdömen från nöjda kunder",
      },
      barbers: {
        title: "Våra barberare",
        subtitle: "Möt vårt professionella team",
      },
    },
    services: {
      title: "Våra tjänster",
      description: "Utforska vårt utbud av premiumtjänster",
      haircut: {
        title: "Hårklippning",
        description: "Professionell hårklippning anpassad efter dina önskemål och ansiktsform.",
      },
      beard: {
        title: "Skäggtrimning",
        description: "Precisionstrimning och formning av skägg med varma handdukar och oljor.",
      },
      luxury: {
        title: "Lyxbehandling",
        description: "Komplett behandling med hårklippning, skäggtrimning, ansiktsbehandling och huvudmassage.",
      },
      kids: {
        title: "Barnklippning",
        description: "Hårklippning för barn upp till 12 år i en vänlig och avslappnad miljö.",
      },
      shave: {
        title: "Traditionell rakning",
        description: "Klassisk rakning med rakhyvel och varma handdukar för en slät och behaglig upplevelse.",
      },
      facial: {
        title: "Ansiktsbehandling",
        description: "Djuprengörande ansiktsbehandling med exfoliering, mask och återfuktande produkter.",
      },
      coloring: {
        title: "Färgning",
        description: "Professionell hår- eller skäggfärgning med högkvalitativa produkter för ett naturligt resultat.",
      },
      styling: {
        title: "Styling",
        description:
          "Professionell styling med förstklassiga produkter för ett perfekt utseende till speciella tillfällen.",
      },
      package: {
        title: "Komplett paket",
        description:
          "Vårt mest exklusiva paket med hårklippning, skäggtrimning, ansiktsbehandling, huvudmassage och styling.",
      },
    },
    booking: {
      title: "Boka tid",
      description: "Boka din nästa barberupplevelse",
      steps: {
        service: "Välj tjänst",
        barber: "Välj barberare",
        date: "Välj datum",
        time: "Välj tid",
        info: "Dina uppgifter",
        confirm: "Bekräfta bokning",
      },
      form: {
        nameLabel: "Ditt namn",
        namePlaceholder: "Ange ditt fullständiga namn",
        emailLabel: "Din e-post",
        emailPlaceholder: "Ange din e-postadress",
        phoneLabel: "Ditt telefonnummer",
        phonePlaceholder: "Ange ditt telefonnummer",
        dateLabel: "Välj datum",
        timeLabel: "Välj tid",
        noTimesAvailable: "Inga tider tillgängliga",
        confirmButton: "Bekräfta bokning",
        successMessage: "Din bokning är bekräftad!",
        errorMessage: "Ett fel uppstod vid bokningen. Försök igen.",
      },
    },
    contact: {
      title: "Kontakta oss",
      description: "Vi ser fram emot att höra från dig",
      info: {
        title: "Kontaktinformation",
        addressTitle: "Adress",
        phoneTitle: "Telefon",
        emailTitle: "E-post",
        hoursTitle: "Öppettider",
      },
      form: {
        title: "Skicka ett meddelande",
        nameLabel: "Ditt namn",
        namePlaceholder: "Ange ditt fullständiga namn",
        emailLabel: "Din e-post",
        emailPlaceholder: "Ange din e-postadress",
        messageLabel: "Ditt meddelande",
        messagePlaceholder: "Skriv ditt meddelande här...",
        submitButton: "Skicka meddelande",
        successTitle: "Tack för ditt meddelande!",
        successMessage: "Vi återkommer till dig så snart som möjligt.",
      },
    },
    admin: {
      login: {
        title: "Admin inloggning",
        description: "Logga in för att hantera bokningar och tillgänglighet",
        emailLabel: "E-post",
        emailPlaceholder: "Ange din e-post",
        passwordLabel: "Lösenord",
        passwordPlaceholder: "Ange ditt lösenord",
        loginButton: "Logga in",
        errorMessage: "Felaktiga inloggningsuppgifter",
      },
      dashboard: {
        title: "Admin Dashboard",
        description: "Hantera bokningar, kunder och tillgänglighet",
        bookings: "Bokningar",
        customers: "Kunder",
        analytics: "Analys",
        availability: "Tillgänglighet",
        welcome: "Välkommen tillbaka",
      },
      button: {
        aria: "Administratörsåtkomst"
      },
    },
    footer: {
      about: "Om oss",
      aboutText: "Barberhaus Stockholm erbjuder premiumtjänster i en lyxig och avslappnad miljö.",
      contact: "Kontakt",
      address: "Storgatan 1, 111 23 Stockholm",
      phone: "+46 70 123 45 67",
      email: "info@barberhaus.se",
      hours: "Öppettider",
      monday: "Måndag: 10:00 - 18:00",
      tuesday: "Tisdag: 10:00 - 18:00",
      wednesday: "Onsdag: 10:00 - 18:00",
      thursday: "Torsdag: 10:00 - 18:00",
      friday: "Fredag: 10:00 - 18:00",
      saturday: "Lördag: 10:00 - 16:00",
      sunday: "Söndag: Stängt",
      rights: "© 2023 Barberhaus Stockholm. Alla rättigheter förbehållna.",
    },
  },
  en: {
    common: {
      bookNow: "Book Now",
      readMore: "Read More",
      loading: "Loading...",
      error: "An error occurred",
      success: "Success!",
      submit: "Submit",
      cancel: "Cancel",
      next: "Next",
      previous: "Previous",
      home: "Home",
      services: "Services",
      booking: "Booking",
      contact: "Contact",
      admin: "Admin",
      login: "Login",
      logout: "Logout",
      email: "Email",
      password: "Password",
      name: "Name",
      phone: "Phone",
      date: "Date",
      time: "Time",
      service: "Service",
      barber: "Barber",
      duration: "Duration",
      price: "Price",
      minutes: "minutes",
      sek: "SEK",
    },
    nav: {
      home: "Home",
      services: "Services",
      booking: "Book Now",
      contact: "Contact",
    },
    home: {
      hero: {
        title: "Premium Barber Experience",
        subtitle: "Where style meets tradition",
        cta: "Book Now",
      },
      services: {
        title: "Our Services",
        subtitle: "Professional grooming for men",
        viewAll: "View all services",
      },
      testimonials: {
        title: "What Our Clients Say",
        subtitle: "Reviews from satisfied customers",
      },
      barbers: {
        title: "Our Barbers",
        subtitle: "Meet our professional team",
      },
    },
    services: {
      title: "Our Services",
      description: "Explore our range of premium services",
      haircut: {
        title: "Haircut",
        description: "Professional haircut tailored to your preferences and face shape.",
      },
      beard: {
        title: "Beard Trim",
        description: "Precision trimming and shaping of beard with hot towels and oils.",
      },
      luxury: {
        title: "Luxury Treatment",
        description: "Complete treatment with haircut, beard trim, facial treatment and head massage.",
      },
      kids: {
        title: "Kids Cut",
        description: "Haircut for children up to 12 years in a friendly and relaxed environment.",
      },
      shave: {
        title: "Traditional Shave",
        description: "Classic shave with straight razor and hot towels for a smooth and comfortable experience.",
      },
      facial: {
        title: "Facial Treatment",
        description: "Deep cleansing facial treatment with exfoliation, mask and moisturizing products.",
      },
      coloring: {
        title: "Coloring",
        description: "Professional hair or beard coloring with high-quality products for a natural result.",
      },
      styling: {
        title: "Styling",
        description: "Professional styling with premium products for a perfect look for special occasions.",
      },
      package: {
        title: "Complete Package",
        description: "Our most exclusive package with haircut, beard trim, facial treatment, head massage and styling.",
      },
    },
    booking: {
      title: "Book Appointment",
      description: "Book your next barber experience",
      steps: {
        service: "Choose Service",
        barber: "Select Barber",
        date: "Pick Date",
        time: "Choose Time",
        info: "Your Information",
        confirm: "Confirm Booking",
      },
      form: {
        nameLabel: "Your Name",
        namePlaceholder: "Enter your full name",
        emailLabel: "Your Email",
        emailPlaceholder: "Enter your email address",
        phoneLabel: "Your Phone Number",
        phonePlaceholder: "Enter your phone number",
        dateLabel: "Select Date",
        timeLabel: "Select Time",
        noTimesAvailable: "No times available",
        confirmButton: "Confirm Booking",
        successMessage: "Your booking is confirmed!",
        errorMessage: "An error occurred during booking. Please try again.",
      },
    },
    contact: {
      title: "Contact Us",
      description: "We look forward to hearing from you",
      info: {
        title: "Contact Information",
        addressTitle: "Address",
        phoneTitle: "Phone",
        emailTitle: "Email",
        hoursTitle: "Opening Hours",
      },
      form: {
        title: "Send a Message",
        nameLabel: "Your Name",
        namePlaceholder: "Enter your full name",
        emailLabel: "Your Email",
        emailPlaceholder: "Enter your email address",
        messageLabel: "Your Message",
        messagePlaceholder: "Write your message here...",
        submitButton: "Send Message",
        successTitle: "Thank you for your message!",
        successMessage: "We will get back to you as soon as possible.",
      },
    },
    admin: {
      login: {
        title: "Admin Login",
        description: "Sign in to manage bookings and availability",
        emailLabel: "Email address",
        emailPlaceholder: "Enter your email",
        passwordLabel: "Password",
        passwordPlaceholder: "Enter your password",
        loginButton: "Login",
        errorMessage: "Invalid login credentials",
      },
      button: {
        aria: "Administrator access"
      },
      dashboard: {
        title: "Admin Dashboard",
        description: "Manage bookings, customers and availability",
        bookings: "Bookings",
        customers: "Customers",
        analytics: "Analytics",
        availability: "Availability",
        welcome: "Welcome back",
      },
    },
    footer: {
      about: "About Us",
      aboutText: "Barberhaus Stockholm offers premium services in a luxurious and relaxed environment.",
      contact: "Contact",
      address: "Storgatan 1, 111 23 Stockholm",
      phone: "+46 70 123 45 67",
      email: "info@barberhaus.se",
      hours: "Opening Hours",
      monday: "Monday: 10:00 - 18:00",
      tuesday: "Tuesday: 10:00 - 18:00",
      wednesday: "Wednesday: 10:00 - 18:00",
      thursday: "Thursday: 10:00 - 18:00",
      friday: "Friday: 10:00 - 18:00",
      saturday: "Saturday: 10:00 - 16:00",
      sunday: "Sunday: Closed",
      rights: "© 2023 Barberhaus Stockholm. All rights reserved.",
    },
  },
  ar: {
    common: {
      bookNow: "احجز الآن",
      readMore: "اقرأ المزيد",
      loading: "جار التحميل...",
      error: "حدث خطأ",
      success: "تم بنجاح!",
      submit: "إرسال",
      cancel: "إلغاء",
      next: "التالي",
      previous: "السابق",
      home: "الرئيسية",
      services: "الخدمات",
      booking: "الحجز",
      contact: "اتصل بنا",
      admin: "المدير",
      login: "تسجيل الدخول",
      logout: "تسجيل الخروج",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      name: "الاسم",
      phone: "الهاتف",
      date: "التاريخ",
      time: "الوقت",
      service: "الخدمة",
      barber: "الحلاق",
      duration: "المدة",
      price: "السعر",
      minutes: "دقائق",
      sek: "كرونة سويدية",
    },
    nav: {
      home: "الرئيسية",
      services: "الخدمات",
      booking: "احجز الآن",
      contact: "اتصل بنا",
    },
    home: {
      hero: {
        title: "تجربة حلاقة فاخرة",
        subtitle: "حيث يلتقي الأسلوب بالتقاليد",
        cta: "احجز الآن",
      },
      services: {
        title: "خدماتنا",
        subtitle: "العناية المهنية للرجال",
        viewAll: "عرض جميع الخدمات",
      },
      testimonials: {
        title: "ما يقوله عملاؤنا",
        subtitle: "آراء من عملاء راضين",
      },
      barbers: {
        title: "الحلاقون لدينا",
        subtitle: "تعرف على فريقنا المحترف",
      },
    },
    services: {
      title: "خدماتنا",
      description: "استكشف مجموعة خدماتنا الفاخرة",
      haircut: {
        title: "قص الشعر",
        description: "قص شعر احترافي مصمم حسب تفضيلاتك وشكل وجهك.",
      },
      beard: {
        title: "تشذيب اللحية",
        description: "تشذيب وتشكيل دقيق للحية مع المناشف الساخنة والزيوت.",
      },
      luxury: {
        title: "علاج فاخر",
        description: "علاج كامل مع قص الشعر وتشذيب اللحية وعلاج الوجه وتدليك الرأس.",
      },
      kids: {
        title: "قص شعر الأطفال",
        description: "قص شعر للأطفال حتى 12 سنة في بيئة ودية ومريحة.",
      },
      shave: {
        title: "حلاقة تقليدية",
        description: "حلاقة كلاسيكية بالموس والمناشف الساخنة لتجربة ناعمة ومريحة.",
      },
      facial: {
        title: "علاج الوجه",
        description: "علاج تنظيف عميق للوجه مع التقشير والقناع ومنتجات الترطيب.",
      },
      coloring: {
        title: "صباغة",
        description: "صباغة احترافية للشعر أو اللحية بمنتجات عالية الجودة لنتيجة طبيعية.",
      },
      styling: {
        title: "تصفيف",
        description: "تصفيف احترافي بمنتجات ممتازة لمظهر مثالي للمناسبات الخاصة.",
      },
      package: {
        title: "الباقة الكاملة",
        description: "باقتنا الأكثر حصرية مع قص الشعر وتشذيب اللحية وعلاج الوجه وتدليك الرأس والتصفيف.",
      },
    },
    booking: {
      title: "حجز موعد",
      description: "احجز تجربة الحلاقة التالية",
      steps: {
        service: "اختر الخدمة",
        barber: "اختر الحلاق",
        date: "اختر التاريخ",
        time: "اختر الوقت",
        info: "معلوماتك",
        confirm: "تأكيد الحجز",
      },
      form: {
        nameLabel: "اسمك",
        namePlaceholder: "أدخل اسمك الكامل",
        emailLabel: "بريدك الإلكتروني",
        emailPlaceholder: "أدخل عنوان بريدك الإلكتروني",
        phoneLabel: "رقم هاتفك",
        phonePlaceholder: "أدخل رقم هاتفك",
        dateLabel: "اختر التاريخ",
        timeLabel: "اختر الوقت",
        noTimesAvailable: "لا توجد أوقات متاحة",
        confirmButton: "تأكيد الحجز",
        successMessage: "تم تأكيد حجزك!",
        errorMessage: "حدث خطأ أثناء الحجز. يرجى المحاولة مرة أخرى.",
      },
    },
    contact: {
      title: "اتصل بنا",
      description: "نتطلع إلى سماع منك",
      info: {
        title: "معلومات الاتصال",
        addressTitle: "العنوان",
        phoneTitle: "الهاتف",
        emailTitle: "البريد الإلكتروني",
        hoursTitle: "ساعات العمل",
      },
      form: {
        title: "أرسل رسالة",
        nameLabel: "اسمك",
        namePlaceholder: "أدخل اسمك الكامل",
        emailLabel: "بريدك الإلكتروني",
        emailPlaceholder: "أدخل عنوان بريدك الإلكتروني",
        messageLabel: "رسالتك",
        messagePlaceholder: "اكتب رسالتك هنا...",
        submitButton: "إرسال الرسالة",
        successTitle: "شكرا لرسالتك!",
        successMessage: "سنعود إليك في أقرب وقت ممكن.",
      },
    },
    admin: {
      login: {
        title: "تسجيل دخول المدير",
        description: "تسجيل الدخول لإدارة الحجوزات والتوفر",
        emailLabel: "البريد الإلكتروني",
        emailPlaceholder: "أدخل بريدك الإلكتروني",
        passwordLabel: "كلمة المرور",
        passwordPlaceholder: "أدخل كلمة المرور",
        loginButton: "تسجيل الدخول",
        errorMessage: "بيانات تسجيل الدخول غير صالحة",
      },
      button: {
        aria: "وصول المسؤول"
      },
      dashboard: {
        title: "لوحة تحكم المدير",
        description: "إدارة الحجوزات والعملاء والتوفر",
        bookings: "الحجوزات",
        customers: "العملاء",
        analytics: "التحليلات",
        availability: "التوفر",
        welcome: "مرحبًا بعودتك",
      },
    },
    footer: {
      about: "من نحن",
      aboutText: "باربرهاوس ستوكهولم يقدم خدمات فاخرة في بيئة فخمة ومريحة.",
      contact: "اتصل بنا",
      address: "ستورجاتان 1، 111 23 ستوكهولم",
      phone: "+46 70 123 45 67",
      email: "info@barberhaus.se",
      hours: "ساعات العمل",
      monday: "الاثنين: 10:00 - 18:00",
      tuesday: "الثلاثاء: 10:00 - 18:00",
      wednesday: "الأربعاء: 10:00 - 18:00",
      thursday: "الخميس: 10:00 - 18:00",
      friday: "الجمعة: 10:00 - 18:00",
      saturday: "السبت: 10:00 - 16:00",
      sunday: "الأحد: مغلق",
      rights: "© 2023 باربرهاوس ستوكهولم. جميع الحقوق محفوظة.",
    },
  },
}

